name: build on push
on:
  push:
    paths-ignore:
      - '.github/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v1
      - name: build
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        run: |
          yarn
          yarn build
          npx netlify-cli deploy --dir=build --prod
